deployment:
  tasks:
    - export DEPLOYPATH=/home/iloveshr/public_html/
    - export LOGFILE=/home/iloveshr/deploy.log

    - echo "=== DEPLOY START $(date) ===" >> $LOGFILE

    # Clean old files (Exclude cgi-bin if necessary, but matching user request)
    - /bin/rm -rf $DEPLOYPATH/* >> $LOGFILE 2>&1

    # Deploy pre-built frontend
    - /bin/cp -R frontend/build/* $DEPLOYPATH >> $LOGFILE 2>&1

    - echo "=== DEPLOY END $(date) ===" >> $LOGFILE
